/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject1;

/**
 *
 * @author kuba
 */
public class PolybiusTableFrame extends javax.swing.JFrame {

    /**
     * Creates new form PolybiusTableFrame
     */
    public PolybiusTableFrame(Character [] tab) {
        initComponents();
        setTable(tab);
    }
    
    public void setTable(Character [] tab){
        polybius_table = tab;
        if (tab.length == 25) {            
            tabElement0Label.setText(tab[0].toString());
            tabElement1Label.setText(tab[1].toString());
            tabElement2Label.setText(tab[2].toString());
            tabElement3Label.setText(tab[3].toString());
            tabElement4Label.setText(tab[4].toString());
            tabElement5Label.setText(tab[5].toString());
            tabElement6Label.setText(tab[6].toString());
            tabElement7Label.setText(tab[7].toString());
            tabElement8Label.setText(tab[8].toString());
            tabElement9Label.setText(tab[9].toString());
            tabElement10Label.setText(tab[10].toString());
            tabElement11Label.setText(tab[11].toString());
            tabElement12Label.setText(tab[12].toString());
            tabElement13Label.setText(tab[13].toString());
            tabElement14Label.setText(tab[14].toString());
            tabElement15Label.setText(tab[15].toString());
            tabElement16Label.setText(tab[16].toString());
            tabElement17Label.setText(tab[17].toString());
            tabElement18Label.setText(tab[18].toString());
            tabElement19Label.setText(tab[19].toString());
            tabElement20Label.setText(tab[20].toString());
            tabElement21Label.setText(tab[21].toString());
            tabElement22Label.setText(tab[22].toString());
            tabElement23Label.setText(tab[23].toString());
            tabElement24Label.setText(tab[24].toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        row1Label = new javax.swing.JLabel();
        row2Label = new javax.swing.JLabel();
        row3Label = new javax.swing.JLabel();
        row4Label = new javax.swing.JLabel();
        row5Label = new javax.swing.JLabel();
        column1Label = new javax.swing.JLabel();
        column2Label = new javax.swing.JLabel();
        column3Label = new javax.swing.JLabel();
        column4Label = new javax.swing.JLabel();
        column5Label = new javax.swing.JLabel();
        tabElement0Label = new javax.swing.JLabel();
        tabElement1Label = new javax.swing.JLabel();
        tabElement2Label = new javax.swing.JLabel();
        tabElement3Label = new javax.swing.JLabel();
        tabElement4Label = new javax.swing.JLabel();
        tabElement5Label = new javax.swing.JLabel();
        tabElement6Label = new javax.swing.JLabel();
        tabElement7Label = new javax.swing.JLabel();
        tabElement8Label = new javax.swing.JLabel();
        tabElement9Label = new javax.swing.JLabel();
        tabElement10Label = new javax.swing.JLabel();
        tabElement11Label = new javax.swing.JLabel();
        tabElement12Label = new javax.swing.JLabel();
        tabElement13Label = new javax.swing.JLabel();
        tabElement14Label = new javax.swing.JLabel();
        tabElement15Label = new javax.swing.JLabel();
        tabElement16Label = new javax.swing.JLabel();
        tabElement17Label = new javax.swing.JLabel();
        tabElement18Label = new javax.swing.JLabel();
        tabElement19Label = new javax.swing.JLabel();
        tabElement20Label = new javax.swing.JLabel();
        tabElement21Label = new javax.swing.JLabel();
        tabElement22Label = new javax.swing.JLabel();
        tabElement23Label = new javax.swing.JLabel();
        tabElement24Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Polybius Table");

        row1Label.setText("1");

        row2Label.setText("2");

        row3Label.setText("3");

        row4Label.setText("4");

        row5Label.setText("5");

        column1Label.setText("1");

        column2Label.setText("2");

        column3Label.setText("3");

        column4Label.setText("4");

        column5Label.setText("5");

        tabElement0Label.setText("a");

        tabElement1Label.setText("a");

        tabElement2Label.setText("a");

        tabElement3Label.setText("a");

        tabElement4Label.setText("a");

        tabElement5Label.setText("a");

        tabElement6Label.setText("a");

        tabElement7Label.setText("a");

        tabElement8Label.setText("a");

        tabElement9Label.setText("a");

        tabElement10Label.setText("a");

        tabElement11Label.setText("a");

        tabElement12Label.setText("a");

        tabElement13Label.setText("a");

        tabElement14Label.setText("a");

        tabElement15Label.setText("a");

        tabElement16Label.setText("a");

        tabElement17Label.setText("a");

        tabElement18Label.setText("a");

        tabElement19Label.setText("a");

        tabElement20Label.setText("a");

        tabElement21Label.setText("a");

        tabElement22Label.setText("a");

        tabElement23Label.setText("a");

        tabElement24Label.setText("a");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(row1Label)
                                    .addComponent(row4Label)
                                    .addComponent(row5Label)
                                    .addComponent(row2Label)
                                    .addComponent(row3Label))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tabElement20Label)
                                    .addComponent(tabElement15Label)
                                    .addComponent(tabElement10Label)
                                    .addComponent(tabElement5Label)
                                    .addComponent(tabElement0Label)))
                            .addComponent(column1Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(column2Label)
                            .addComponent(tabElement21Label)
                            .addComponent(tabElement16Label)
                            .addComponent(tabElement11Label)
                            .addComponent(tabElement6Label)
                            .addComponent(tabElement1Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(column3Label)
                            .addComponent(tabElement22Label)
                            .addComponent(tabElement17Label)
                            .addComponent(tabElement12Label)
                            .addComponent(tabElement7Label)
                            .addComponent(tabElement2Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(column4Label)
                            .addComponent(tabElement23Label)
                            .addComponent(tabElement18Label)
                            .addComponent(tabElement13Label)
                            .addComponent(tabElement8Label)
                            .addComponent(tabElement3Label))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabElement24Label)
                            .addComponent(tabElement19Label)
                            .addComponent(tabElement14Label)
                            .addComponent(tabElement9Label)
                            .addComponent(tabElement4Label)
                            .addComponent(column5Label))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleLabel)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(column1Label)
                    .addComponent(column2Label)
                    .addComponent(column3Label)
                    .addComponent(column4Label)
                    .addComponent(column5Label))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(row1Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(row2Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(row3Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(row4Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(row5Label))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabElement0Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement5Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement10Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement15Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement20Label))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tabElement2Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tabElement7Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tabElement12Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tabElement17Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tabElement22Label))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(tabElement1Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tabElement6Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tabElement11Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tabElement16Label)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tabElement21Label)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabElement3Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement8Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement13Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement18Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement23Label))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabElement4Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement9Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement14Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement19Label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tabElement24Label)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolybiusTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolybiusTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolybiusTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolybiusTableFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Character [] temp_tab = null;
                new PolybiusTableFrame(temp_tab).setVisible(true);
            }
        });
    }
    private Character [] polybius_table = {'a','b','c','d','e','f','g','h','i','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'};

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel column1Label;
    private javax.swing.JLabel column2Label;
    private javax.swing.JLabel column3Label;
    private javax.swing.JLabel column4Label;
    private javax.swing.JLabel column5Label;
    private javax.swing.JLabel row1Label;
    private javax.swing.JLabel row2Label;
    private javax.swing.JLabel row3Label;
    private javax.swing.JLabel row4Label;
    private javax.swing.JLabel row5Label;
    private javax.swing.JLabel tabElement0Label;
    private javax.swing.JLabel tabElement10Label;
    private javax.swing.JLabel tabElement11Label;
    private javax.swing.JLabel tabElement12Label;
    private javax.swing.JLabel tabElement13Label;
    private javax.swing.JLabel tabElement14Label;
    private javax.swing.JLabel tabElement15Label;
    private javax.swing.JLabel tabElement16Label;
    private javax.swing.JLabel tabElement17Label;
    private javax.swing.JLabel tabElement18Label;
    private javax.swing.JLabel tabElement19Label;
    private javax.swing.JLabel tabElement1Label;
    private javax.swing.JLabel tabElement20Label;
    private javax.swing.JLabel tabElement21Label;
    private javax.swing.JLabel tabElement22Label;
    private javax.swing.JLabel tabElement23Label;
    private javax.swing.JLabel tabElement24Label;
    private javax.swing.JLabel tabElement2Label;
    private javax.swing.JLabel tabElement3Label;
    private javax.swing.JLabel tabElement4Label;
    private javax.swing.JLabel tabElement5Label;
    private javax.swing.JLabel tabElement6Label;
    private javax.swing.JLabel tabElement7Label;
    private javax.swing.JLabel tabElement8Label;
    private javax.swing.JLabel tabElement9Label;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
